### ISSUE TITLE
Footer is not sticky

### ISSUE THREAD

**Issue by martnu** [marcusf/memory-tapes#3]
Great app! 

Just a problem when having the client so small that the scrollbar appears. The footer gets stuck in middle while scrolling.

**Comment by marcusf** [comment]
Thanks, good point. I wrestled a bit with the viewport to get the thing to stick to max(document height, viewport height), but for some reason couldn't get it to work and decided to go with this for now... Seems that came back to bite me... :)

**Comment by marcusf** [comment]
I'm looking at rewriting the UI entirely (to get rid of the damn drop down box). Busted initial sketches are commited on the branch bloedel.

**Comment by thelinmichael** [comment]
When is this coming? We're still waiting, why don't you care about devs?
